import type { DailyExternalAggregate, ExternalCandidateExplanationArtifact } from "../externalDiscovery/types.ts";

const TARGET_DIAGNOSTICS = {
  event_count: 0,
  project_event_count: 0,
  paper_event_count: 0,
  product_event_count: 0,
  topic_event_count: 0,
  events_with_target_url_count: 0,
  events_with_repo_url_count: 0,
  events_with_paper_url_count: 0,
  candidates_with_target_url_count: 0,
  title_only_project_rejected_count: 0,
  official_query_name_rejected_count: 0,
  unbound_target_event_count: 0,
};

function baseAggregate(overrides: Partial<DailyExternalAggregate> = {}): DailyExternalAggregate {
  return {
    schema_version: "external-discovery.aggregate.v1",
    date: "2026-06-29",
    generated_at: "2026-06-29T08:00:00.000Z",
    provider: "agent-reach",
    provider_run_id: "fixture-run",
    status: "ok",
    status_reason: "fixture ok",
    source_input_ref: "fixture",
    source_input_hash: "fixture-hash",
    public_safe: true,
    redaction_policy_version: "external-redaction.v1",
    contains_raw_text: false,
    contains_profile_urls: false,
    event_count: 3,
    accepted_event_count: 3,
    rejected_event_count: 0,
    platform_counts: {
      x_twitter: 1,
      reddit: 1,
      official_blog: 1,
    },
    derived_signal_kind_counts: {
      discovery: 2,
      evidence: 1,
    },
    direction_label_counts: {
      "workflow-automation-agent": 2,
    },
    evidence_sources: [],
    project_evidence: [],
    direction_evidence: [],
    observation_candidates: [],
    audit: {
      coverage: {
        x_twitter: { status: "ok", reason: "fixture ok" },
        reddit: { status: "ok", reason: "fixture ok" },
        hacker_news: { status: "zero_relevant_results", reason: "executed_without_relevant_results" },
        official_web: { status: "not_configured", reason: "not_configured" },
        official_blog: { status: "ok", reason: "fixture ok" },
      },
      target_extraction_diagnostics: { ...TARGET_DIAGNOSTICS, event_count: 3, project_event_count: 2, topic_event_count: 1 },
      rejected_events: [],
      warnings: [],
    },
    ...overrides,
  };
}

export function makeOkAgentReachAggregate(): DailyExternalAggregate {
  return baseAggregate({
    evidence_sources: [
      {
        source_id: "src-x",
        event_id: "event-x",
        platform: "x_twitter",
        raw_event_kind: "mention",
        derived_signal_kinds: ["discovery"],
        direction_labels: ["workflow-automation-agent"],
        source_url: "https://x.com/acme/status/1800000000000000000",
        source_title: "AgentFlow launch discussion",
        source_published_at: "2026-06-29T06:00:00.000Z",
        observed_at: "2026-06-29T07:00:00.000Z",
        target_type: "project",
        target_name: "AgentFlow",
        target_url: "https://github.com/acme/agentflow",
        actor_type: "team",
        actor_tier: "proven",
        metrics: {
          likes: 18,
          reposts: 4,
          comments: 6,
        },
      },
      {
        source_id: "src-reddit",
        event_id: "event-reddit",
        platform: "reddit",
        raw_event_kind: "discussion",
        derived_signal_kinds: ["evidence"],
        direction_labels: ["workflow-automation-agent"],
        source_url: "https://www.reddit.com/r/LocalLLaMA/comments/abc/teams_comparing_agentflow/",
        source_title: "Teams comparing AgentFlow for workflow automation",
        source_published_at: "2026-06-29T05:30:00.000Z",
        observed_at: "2026-06-29T07:05:00.000Z",
        target_type: "project",
        target_name: "AgentFlow",
        target_url: "https://github.com/acme/agentflow",
        actor_type: "community",
        actor_tier: "watch",
        metrics: {
          upvotes: 42,
          comments: 11,
          replies: 3,
        },
      },
      {
        source_id: "src-official",
        event_id: "event-official",
        platform: "official_blog",
        raw_event_kind: "official_release",
        derived_signal_kinds: ["discovery"],
        direction_labels: ["office-agent"],
        source_url: "https://example.com/agentdesk-release",
        source_title: "AgentDesk official release",
        source_published_at: "2026-06-29T04:00:00.000Z",
        observed_at: "2026-06-29T07:10:00.000Z",
        target_type: "product",
        target_name: "AgentDesk",
        target_url: "https://example.com/agentdesk",
        actor_type: "team",
        actor_tier: "core",
        metrics: {
          likes: 9,
        },
      },
    ],
    project_evidence: [
      {
        evidence_id: "ev-agentflow",
        event_ids: ["event-x", "event-reddit"],
        scope: "project",
        target_key: "https://github.com/acme/agentflow",
        derived_signal_kinds: ["discovery", "evidence"],
        direction_labels: ["workflow-automation-agent"],
        platforms: ["x_twitter", "reddit"],
        named_registry_actors: [],
        actor_tiers: { proven: 1, watch: 2 },
        actor_types: { team: 1, community: 2 },
        mention_count: 4,
        distinct_actor_count: 3,
        top_tier_actor_count: 1,
        first_seen_at: "2026-06-29T05:30:00.000Z",
        last_seen_at: "2026-06-29T07:05:00.000Z",
        active_day_count: 1,
        cross_platform: true,
        authority_summary_cn: "团队和社区都在讨论。",
        intensity_summary_cn: "短时间内出现多条讨论。",
        persistence_summary_cn: "当前仍是单日快照。",
        caveats: ["仍需 GitHub / Trendshift 主链路确认。"],
      },
      {
        evidence_id: "ev-agentdesk",
        event_ids: ["event-official"],
        scope: "project",
        target_key: "https://example.com/agentdesk",
        derived_signal_kinds: ["discovery"],
        direction_labels: ["office-agent"],
        platforms: ["official_blog"],
        named_registry_actors: [],
        actor_tiers: { core: 1 },
        actor_types: { team: 1 },
        mention_count: 1,
        distinct_actor_count: 1,
        top_tier_actor_count: 1,
        first_seen_at: "2026-06-29T04:00:00.000Z",
        last_seen_at: "2026-06-29T07:10:00.000Z",
        active_day_count: 1,
        cross_platform: false,
        authority_summary_cn: "官方博客发布。",
        intensity_summary_cn: "官方发布信号。",
        persistence_summary_cn: "当前仍是单日快照。",
        caveats: ["官方发布不等于主榜结论。"],
      },
    ],
    direction_evidence: [
      {
        evidence_id: "ev-workflow-direction",
        event_ids: ["event-x", "event-reddit"],
        scope: "direction",
        target_key: "workflow-automation-agent",
        derived_signal_kinds: ["discovery"],
        direction_labels: ["workflow-automation-agent"],
        platforms: ["x_twitter", "reddit"],
        named_registry_actors: [],
        actor_tiers: { proven: 1, watch: 2 },
        actor_types: { team: 1, community: 2 },
        mention_count: 4,
        distinct_actor_count: 3,
        top_tier_actor_count: 1,
        first_seen_at: "2026-06-29T05:30:00.000Z",
        last_seen_at: "2026-06-29T07:05:00.000Z",
        active_day_count: 1,
        cross_platform: true,
        authority_summary_cn: "工作流自动化方向有外部讨论。",
        intensity_summary_cn: "方向线索来自多平台。",
        persistence_summary_cn: "只有单日数据。",
        caveats: ["不能画成多日趋势。"],
      },
    ],
    observation_candidates: [
      {
        candidate_id: "cand-agentflow",
        scope: "project",
        candidate_kind: "new_external_discovery",
        target_type: "project",
        target_key: "https://github.com/acme/agentflow",
        display_name: "AgentFlow",
        target_url: "https://github.com/acme/agentflow",
        repo_url: "https://github.com/acme/agentflow",
        direction_labels: ["workflow-automation-agent"],
        binding_confidence: "high",
        evidence_ids: ["ev-agentflow"],
        evidence_summary_cn: "X 与 Reddit 同时出现 AgentFlow 讨论。",
        qualification: "needs_primary_confirmation",
        can_enter_daily: true,
        can_enter_weekly: false,
        cannot_be_primary_conclusion: true,
        caveats: ["外部信号只能作为次级判断。"],
        external_attention_score: 72,
        display_bucket: "new_discoveries",
        display_reasons: ["跨平台讨论", "仍需主源确认"],
      },
      {
        candidate_id: "cand-agentdesk",
        scope: "project",
        candidate_kind: "external_evidence_boost",
        target_type: "product",
        target_key: "https://example.com/agentdesk",
        display_name: "AgentDesk",
        target_url: "https://example.com/agentdesk",
        direction_labels: ["office-agent"],
        binding_confidence: "medium",
        evidence_ids: ["ev-agentdesk"],
        evidence_summary_cn: "官方博客出现 AgentDesk 发布。",
        qualification: "supporting_evidence_only",
        can_enter_daily: false,
        can_enter_weekly: true,
        cannot_be_primary_conclusion: true,
        caveats: ["官方信号仍需与主链路分离。"],
        external_attention_score: 49,
        display_bucket: "official_releases",
        display_reasons: ["官方发布"],
      },
    ],
  });
}

export function makeAgentReachCandidateExplanationsArtifact(
  overrides: Partial<ExternalCandidateExplanationArtifact> = {},
): ExternalCandidateExplanationArtifact {
  return {
    schema_version: "external-discovery.candidate-explanations.v1",
    date: "2026-06-29",
    generated_at: "2026-06-29T08:10:00.000Z",
    provider: "deepseek",
    explanation_policy_version: "candidate-explanations.v1",
    aggregate_source_input_hash: "fixture-hash",
    aggregate_generated_at: "2026-06-29T08:00:00.000Z",
    input_context_hash: "fixture-context-hash",
    public_safe: true,
    redaction_policy_version: "external-redaction.v1",
    contains_raw_text: false,
    contains_profile_urls: false,
    status: "ok",
    explanations: [
      {
        candidate_key: "project:https://github.com/acme/agentflow",
        candidate_kind: "project",
        target_key: "https://github.com/acme/agentflow",
        explanation_scope: "bound_object",
        what_it_is_cn: "AgentFlow 是一个已绑定 GitHub repo 的工作流自动化项目候选。",
        why_watch_cn: "X 和 Reddit 同时讨论 AgentFlow，适合作为外部层新发现继续观察。",
        summary_confidence: "medium",
        summary_source: "llm",
        evidence_ids: ["ev-agentflow"],
        platforms: ["x_twitter", "reddit"],
        caveats: ["仍需 GitHub 主链路确认活跃度。"],
        generated_at: "2026-06-29T08:10:00.000Z",
      },
    ],
    audit: {
      eligible_count: 1,
      attempted_count: 1,
      accepted_count: 1,
      enhanced_count: 1,
      rejected_count: 0,
      fallback_count: 0,
      warnings: [],
    },
    ...overrides,
  };
}

export function makePartialAgentReachAggregate(): DailyExternalAggregate {
  return baseAggregate({
    status: "partial",
    status_reason: "x_twitter timeout; reddit ok",
    audit: {
      ...baseAggregate().audit,
      coverage: {
        x_twitter: { status: "partial", reason: "timeout", warnings: ["runner_timeout"] },
        reddit: { status: "ok", reason: "ok" },
        hacker_news: { status: "zero_relevant_results", reason: "executed_without_relevant_results" },
      },
      warnings: [{ reason_code: "x_twitter_partial", reason_detail: "x_twitter partial" }],
    },
  });
}

export function makeFailedAgentReachAggregate(): DailyExternalAggregate {
  return baseAggregate({
    status: "failed",
    status_reason: "provider failed before aggregation",
    event_count: 0,
    accepted_event_count: 0,
    rejected_event_count: 0,
    platform_counts: {},
    evidence_sources: [],
    project_evidence: [],
    direction_evidence: [],
    observation_candidates: [],
    audit: {
      ...baseAggregate().audit,
      coverage: {
        x_twitter: { status: "failed", reason: "runner_failed" },
        reddit: { status: "failed", reason: "runner_failed" },
      },
      warnings: [{ reason_code: "provider_failed", reason_detail: "provider_failed" }],
    },
  });
}

export function makeEmptyAgentReachAggregate(): DailyExternalAggregate {
  return baseAggregate({
    status: "ok",
    status_reason: "executed without candidates",
    event_count: 0,
    accepted_event_count: 0,
    rejected_event_count: 0,
    platform_counts: {},
    evidence_sources: [],
    project_evidence: [],
    direction_evidence: [],
    observation_candidates: [],
    audit: {
      ...baseAggregate().audit,
      coverage: {
        x_twitter: { status: "zero_relevant_results", reason: "executed_without_relevant_results" },
        reddit: { status: "ok", reason: "ok" },
      },
    },
  });
}
