export type UiLang = "zh" | "en";

const COPY = {
  zh: {
    productName: "趋势雷达",
    productSubtitle: "可视控制台",
    envLocalFirst: "本地优先",
    envArtifactFirst: "产物优先",
    envReadFirst: "只读消费",
    navOverview: "首页",
    navProjects: "项目库",
    navWeekly: "本周趋势",
    navRunHealth: "数据状态",
    navKb: "资料卡",
    langLabel: "语言",
    langZh: "中文",
    langEn: "English",
    contextBar: "上下文栏",
    contextLabel: "当前上下文",
    artifactTime: "产物时间",
    topStatus: "顶层状态",
    mode: "模式",
    freshness: "新鲜度",
    statusLabel: "状态",
    enabledLabel: "启用",
    countLabel: "数量",
    notesLabel: "备注",
    interestProfile: "兴趣方向",
    interestProfileHint: "在这里自由输入你关心的方向、主题或关键词，保存后会写回 config.yaml 并持久化给后端消费。",
    interestCurrent: "当前兴趣",
    interestEmpty: "未设置，当前不会触发个性化兴趣加权。",
    interestAutoWeight: "支持逗号、换行或顿号分隔；系统会按等权重保存。如果清空，则自动关闭兴趣画像。",
    interestInputLabel: "兴趣关键词",
    interestInputPlaceholder: "例如：multi-agent, code review, browser automation",
    savePreferences: "保存兴趣方向",
    preferencesSaved: "兴趣方向已保存。",
    preferencesSaveFailed: "兴趣方向保存失败，请检查配置文件可写性。",
    verifyStatusLabel: "校验状态",
    metricsAppliedLabel: "指标已应用",
    weeklyJudgeable: "可判断",
    enhancementStatusLabel: "增强状态",
    auditContextLabel: "审计上下文",
    overallJudgmentLabel: "总体判断",
    coreTrendCountLabel: "核心趋势数",
    weakSignalCountLabel: "弱信号数",
    watchNextLabel: "继续跟进",
    evidenceSummaryLabel: "证据摘要",
    strengthLabel: "强度",
    globalStatusBanner: "当前状态",
    noBlockingNotes: "当前没有额外阻塞说明。",
    runTrustSummary: "这批数据靠不靠谱",
    sourceHealthSummary: "数据来源情况",
    topDecisions: "今日重点项目",
    projectIntroduction: "项目介绍",
    selectionReason: "入选原因",
    risksAndActions: "风险与建议动作",
    navigationActions: "快捷操作",
    openRunHealth: "查看数据状态",
    openWeekly: "看本周趋势",
    projects: "项目列表",
    projectDetail: "项目详情",
    detailSurface: "详情承载区",
    selectProjectHint: "选择一个项目以查看证据、风险和知识卡片入口。",
    projectNotFound: "当前 artifact 上下文中未找到该项目。",
    close: "关闭",
    projectIdentity: "项目身份",
    scoreAndEvidence: "分数与证据",
    riskAndNextActions: "风险与下一步动作",
    runAuditContext: "运行 / 审计上下文",
    kbPreview: "知识卡片预览",
    openKbCard: "打开知识卡片",
    weeklyTrustSummary: "周视图可信度摘要",
    overallWeeklyJudgment: "周视图总体判断",
    coreTrendCards: "核心趋势卡片",
    weakSignals: "弱信号 / 下周观察",
    noWeeklyTrend: "本周还没有形成稳定趋势卡片。",
    noWeakSignals: "当前没有需要单独跟进的弱信号。",
    supportingProjects: "支撑项目",
    verifySummary: "校验结果摘要",
    sourceStatusTable: "来源状态表",
    githubAuditTable: "GitHub enrichment 审计表",
    failureNotes: "失败 / 空态 / 降级说明",
    recommendedActions: "建议动作",
    kbIndex: "资料卡索引",
    kbCard: "资料卡",
    kbMissing: "资料卡未生成 / 不存在",
    kbSelectHint: "从索引中选择一张资料卡，查看机器区和人工区内容。",
    cardReader: "卡片阅读器",
    machineSection: "机器区",
    humanSection: "人工区",
    linkedContext: "关联上下文",
    noHumanSection: "该知识卡片未包含人工区内容",
    none: "无",
    unknown: "未知",
    unavailable: "不可用",
    missing: "缺失",
    score: "分数",
    paradigm: "范式",
    persistence: "持续性",
    confidence: "置信度",
    topEvidence: "顶层证据",
    risks: "风险",
    nextActions: "下一步动作",
    sourceView: "来源视图",
    date: "日期",
    windowEnd: "时间窗结束",
    trendKey: "趋势键",
    updatedAt: "更新时间",
    rulesOnly: "规则模式",
    agentPartial: "部分代理增强",
    agentFull: "完整代理增强",
    ready: "可用",
    degraded: "降级",
    stale: "陈旧",
    failed: "失败",
    empty: "空态",
    notJudgeable: "暂不可判断",
    judgeableYes: "是",
    judgeableNo: "否",
    active: "活跃",
    disabled: "已禁用",
    fallbackPartial: "部分回退",
    auditMissing: "审计缺失",
    pureReadOnlyNote: "语言切换仅影响界面文案，不改写底层 artifact。",
  },
  en: {
    productName: "Trend Radar",
    productSubtitle: "Visual Console",
    envLocalFirst: "local-first",
    envArtifactFirst: "artifact-first",
    envReadFirst: "read-first",
    navOverview: "Overview",
    navProjects: "Projects",
    navWeekly: "Weekly",
    navRunHealth: "Run Health",
    navKb: "Knowledge Base",
    langLabel: "Language",
    langZh: "Chinese",
    langEn: "English",
    contextBar: "Context Bar",
    contextLabel: "Context",
    artifactTime: "Artifact Time",
    topStatus: "Top Status",
    mode: "Mode",
    freshness: "Freshness",
    statusLabel: "Status",
    enabledLabel: "Enabled",
    countLabel: "Count",
    notesLabel: "Notes",
    interestProfile: "Interest Profile",
    interestProfileHint: "Enter any directions, themes, or keywords you care about. Saving writes them back into config.yaml for persistent backend consumption.",
    interestCurrent: "Current Interests",
    interestEmpty: "No saved interests yet, so personalized relevance remains disabled.",
    interestAutoWeight: "Separate items with commas or new lines. Saved interests use equal weights, and clearing everything disables the profile.",
    interestInputLabel: "Interest Keywords",
    interestInputPlaceholder: "For example: multi-agent, code review, browser automation",
    savePreferences: "Save Interests",
    preferencesSaved: "Interest profile saved.",
    preferencesSaveFailed: "Failed to save the interest profile. Check whether config.yaml is writable.",
    verifyStatusLabel: "Verify Status",
    metricsAppliedLabel: "Metrics Applied",
    weeklyJudgeable: "Judgeable",
    enhancementStatusLabel: "Enhancement Status",
    auditContextLabel: "Audit Context",
    overallJudgmentLabel: "Overall Judgment",
    coreTrendCountLabel: "Core Trend Count",
    weakSignalCountLabel: "Weak Signal Count",
    watchNextLabel: "Watch Next",
    evidenceSummaryLabel: "Evidence Summary",
    strengthLabel: "Strength",
    globalStatusBanner: "Global Status Banner",
    noBlockingNotes: "No blocking notes.",
    runTrustSummary: "Run Trust Summary",
    sourceHealthSummary: "Source Health Summary",
    topDecisions: "Top Decisions",
    projectIntroduction: "Project Introduction",
    selectionReason: "Why It Matters Today",
    risksAndActions: "Risks and Recommended Actions",
    navigationActions: "Navigation Actions",
    openRunHealth: "Open Run Health",
    openWeekly: "Open Weekly",
    projects: "Projects",
    projectDetail: "Project Detail",
    detailSurface: "Detail Surface",
    selectProjectHint: "Select a project to inspect evidence, risks, and KB links.",
    projectNotFound: "Project not found in the current artifact context.",
    close: "Close",
    projectIdentity: "Project Identity",
    scoreAndEvidence: "Score and Evidence",
    riskAndNextActions: "Risk and Next Actions",
    runAuditContext: "Run / Audit Context",
    kbPreview: "Knowledge Card Preview",
    openKbCard: "Open KB Card",
    weeklyTrustSummary: "Weekly Trust Summary",
    overallWeeklyJudgment: "Overall Weekly Judgment",
    coreTrendCards: "Core Trend Cards",
    weakSignals: "Weak Signals / Watch Next",
    noWeeklyTrend: "No stable weekly trend cards are available yet.",
    noWeakSignals: "There are no weak signals that need separate follow-up right now.",
    supportingProjects: "Supporting Projects",
    verifySummary: "Verify Result Summary",
    sourceStatusTable: "Source Status Table",
    githubAuditTable: "GitHub Enrichment Audit Table",
    failureNotes: "Failure / Empty / Fallback Notes",
    recommendedActions: "Recommended Actions",
    kbIndex: "KB Index",
    kbCard: "KB Card",
    kbMissing: "KB card is missing or has not been generated.",
    kbSelectHint: "Select a knowledge card from the index to inspect machine and human sections.",
    cardReader: "Card Reader",
    machineSection: "Machine Section",
    humanSection: "Human Section",
    linkedContext: "Linked Context",
    noHumanSection: "This knowledge card does not include a human section.",
    none: "none",
    unknown: "unknown",
    unavailable: "unavailable",
    missing: "missing",
    score: "Score",
    paradigm: "Paradigm",
    persistence: "Persistence",
    confidence: "Confidence",
    topEvidence: "Top Evidence",
    risks: "Risks",
    nextActions: "Next Actions",
    sourceView: "Source View",
    date: "Date",
    windowEnd: "Window End",
    trendKey: "Trend Key",
    updatedAt: "Updated At",
    rulesOnly: "rules-only",
    agentPartial: "agent-partial",
    agentFull: "agent-full",
    ready: "ready",
    degraded: "degraded",
    stale: "stale",
    failed: "failed",
    empty: "empty",
    notJudgeable: "not-judgeable",
    judgeableYes: "yes",
    judgeableNo: "no",
    active: "active",
    disabled: "disabled",
    fallbackPartial: "fallback/partial",
    auditMissing: "audit-missing",
    pureReadOnlyNote: "Language switching only changes UI copy and safe display mappings; it does not rewrite underlying artifacts.",
  },
} as const;

export type UiCopy = (typeof COPY)[UiLang];

export function copy(lang: UiLang): UiCopy {
  return COPY[lang];
}
