import type { UiLang } from "./ossTypes.ts";

const COPY = {
  zh: {
    productName: "趋势雷达",
    productSubtitle: "VISUAL CONSOLE",
    navOverview: "首页",
    navProjects: "项目库",
    navWeekly: "本周趋势",
    navRunHealth: "数据状态",
    navObserver: "新兴潜力项目",
    navKb: "资料卡",
    badgeOverview: "今日优先",
    badgeOverviewHint: "先看最值得继续跟进的项目",
    trustSummary: "可信度摘要",
    sourceHealth: "来源健康",
    actionRail: "后续动作",
    weeklyEntry: "周趋势入口",
    openWeekly: "查看本周趋势",
    openProjects: "查看项目库",
    openRunHealth: "查看数据状态",
    openRepo: "GitHub 仓库",
    topProjects: "今天最值得先看的项目",
    projectReasons: "为什么出现",
    projectList: "项目列表",
    selectedDetail: "详情面板",
    noSelection: "选择一个项目查看证据、风险与知识卡入口。",
    verifySummary: "校验摘要",
    coverageAtlas: "覆盖情况",
    gapLedger: "缺口台账",
    observerStage: "观察工作台",
    kbReader: "知识卡阅读器",
    noKb: "当前没有可展示的知识卡。",
    noObserver: "当前没有观察候选。",
    noWeekly: "当前还没有形成稳定的周趋势卡片。",
    missionHealth: "发现链路状态",
    themeLight: "浅色",
    themeDark: "深色",
    langLabel: "语言",
    langZh: "中",
    langEn: "EN",
    generatedAt: "生成时间",
    status: "状态",
    freshness: "新鲜度",
    score: "分数",
    confidence: "置信度",
    paradigm: "范式",
    persistence: "持续性",
    none: "无",
    close: "关闭",
    risks: "风险",
    nextActions: "下一步动作",
    supportingProjects: "支撑项目",
    projectIdentity: "项目身份",
    kbPreview: "知识卡预览",
    openKbCard: "打开知识卡",
    ready: "就绪",
    degraded: "降级",
    stale: "过期",
    failed: "失败",
    empty: "为空",
    notJudgeable: "暂不可判定",
    rulesOnly: "仅规则",
    agentPartial: "Agent 部分增强",
    agentFull: "Agent 全量增强",
    unknown: "未知",
    contextBar: "上下文栏",
    contextLabel: "上下文",
    artifactTime: "产物时间",
    topStatus: "顶部状态",
    mode: "模式",
    detailSurface: "详情面板",
    projectDetail: "项目详情",
    projectNotFound: "没有找到对应项目。",
    selectProjectHint: "从左侧选择一个项目以继续下钻。",
    date: "日期",
    windowEnd: "窗口结束",
    trendKey: "趋势键",
    sourceView: "来源视图",
    updatedAt: "更新时间",
    scoreAndEvidence: "评分与证据",
    projectIntroduction: "项目简介",
    selectionReason: "入选原因",
    runAuditContext: "运行审计上下文",
    langSwitch: "语言切换",
    topEvidence: "关键证据",
  },
  en: {
    productName: "Trend Radar",
    productSubtitle: "VISUAL CONSOLE",
    navOverview: "Overview",
    navProjects: "Projects",
    navWeekly: "Weekly",
    navRunHealth: "Run Health",
    navObserver: "Observer",
    navKb: "Knowledge Base",
    badgeOverview: "Today First",
    badgeOverviewHint: "Start with the most actionable projects",
    trustSummary: "Trust Summary",
    sourceHealth: "Source Health",
    actionRail: "Next Actions",
    weeklyEntry: "Weekly Entry",
    openWeekly: "Open Weekly",
    openProjects: "Open Projects",
    openRunHealth: "Open Run Health",
    openRepo: "GitHub Repo",
    topProjects: "Projects worth reading first",
    projectReasons: "Why it appears",
    projectList: "Project List",
    selectedDetail: "Detail Panel",
    noSelection: "Select a project to inspect evidence, risks, and KB entry points.",
    verifySummary: "Verify Summary",
    coverageAtlas: "Coverage Atlas",
    gapLedger: "Gap Ledger",
    observerStage: "Observer Workbench",
    kbReader: "KB Reader",
    noKb: "No knowledge card is available yet.",
    noObserver: "No observer candidates are available right now.",
    noWeekly: "No stable weekly trend cards are available yet.",
    missionHealth: "Discovery Status",
    themeLight: "Light",
    themeDark: "Dark",
    langLabel: "Language",
    langZh: "ZH",
    langEn: "EN",
    generatedAt: "Generated At",
    status: "Status",
    freshness: "Freshness",
    score: "Score",
    confidence: "Confidence",
    paradigm: "Paradigm",
    persistence: "Persistence",
    none: "none",
    close: "Close",
    risks: "Risks",
    nextActions: "Next Actions",
    supportingProjects: "Supporting Projects",
    projectIdentity: "Project Identity",
    kbPreview: "KB Preview",
    openKbCard: "Open KB Card",
    ready: "Ready",
    degraded: "Degraded",
    stale: "Stale",
    failed: "Failed",
    empty: "Empty",
    notJudgeable: "Not Judgeable",
    rulesOnly: "Rules Only",
    agentPartial: "Agent Partial",
    agentFull: "Agent Full",
    unknown: "Unknown",
    contextBar: "Context Bar",
    contextLabel: "Context",
    artifactTime: "Artifact Time",
    topStatus: "Top Status",
    mode: "Mode",
    detailSurface: "Detail Surface",
    projectDetail: "Project Detail",
    projectNotFound: "The requested project could not be found.",
    selectProjectHint: "Select a project from the left to keep drilling down.",
    date: "Date",
    windowEnd: "Window End",
    trendKey: "Trend Key",
    sourceView: "Source View",
    updatedAt: "Updated At",
    scoreAndEvidence: "Score And Evidence",
    projectIntroduction: "Project Introduction",
    selectionReason: "Selection Reason",
    runAuditContext: "Run Audit Context",
    langSwitch: "Language Switch",
    topEvidence: "Top Evidence",
  },
} as const;

export type OssUiCopy = (typeof COPY)[UiLang];

export function copy(lang: UiLang): OssUiCopy {
  return COPY[lang];
}
